apiVersion: apps/v1
kind: Deployment
metadata:
  name: dify-external-kb-server
  labels:
    app: dify-external-kb-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dify-external-kb-server
  template:
    metadata:
      labels:
        app: dify-external-kb-server
    spec:
      containers:
      - name: dify-external-kb-server
        image: registry.cn-hangzhou.aliyuncs.com/t9k/dify-external-kb-server:20250509
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        env:
        # Milvus连接配置
        - name: MILVUS_HOST
          valueFrom:
            configMapKeyRef:
              name: dify-external-kb-server-config
              key: milvus_host
        - name: MILVUS_PORT
          valueFrom:
            configMapKeyRef:
              name: dify-external-kb-server-config
              key: milvus_port
        # 搜索模式配置
        - name: SEARCH_MODE
          valueFrom:
            configMapKeyRef:
              name: dify-external-kb-server-config
              key: search_mode
        # 密集向量配置
        - name: DENSE_FIELD
          valueFrom:
            configMapKeyRef:
              name: dify-external-kb-server-config
              key: dense_field
        - name: DENSE_METRIC_TYPE
          valueFrom:
            configMapKeyRef:
              name: dify-external-kb-server-config
              key: dense_metric_type
        # 稀疏向量配置
        - name: SPARSE_FIELD
          valueFrom:
            configMapKeyRef:
              name: dify-external-kb-server-config
              key: sparse_field
        - name: SPARSE_METRIC_TYPE
          valueFrom:
            configMapKeyRef:
              name: dify-external-kb-server-config
              key: sparse_metric_type
        # 混合搜索配置
        - name: HYBRID_RRF_K
          valueFrom:
            configMapKeyRef:
              name: dify-external-kb-server-config
              key: hybrid_rrf_k
        # 嵌入模型配置
        - name: USE_FP16
          valueFrom:
            configMapKeyRef:
              name: dify-external-kb-server-config
              key: use_fp16
        - name: DEVICE
          valueFrom:
            configMapKeyRef:
              name: dify-external-kb-server-config
              key: device
        # API密钥
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: dify-external-kb-server-secret
              key: api_key
        # Milvus Token
        - name: MILVUS_TOKEN
          valueFrom:
            secretKeyRef:
              name: dify-external-kb-server-secret
              key: milvus_token
        # 调试模式
        - name: DEBUG_MODE
          value: "false"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "4"
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 15
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: dify-external-kb-server
spec:
  selector:
    app: dify-external-kb-server
  ports:
  - port: 80
    targetPort: 5001
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dify-external-kb-server-config
data:
  # Milvus连接配置
  milvus_host: "milvus-standalone"
  milvus_port: "19530"
  
  # 默认搜索模式
  search_mode: "hybrid"
  
  # 密集向量配置
  dense_field: "dense_vector"
  dense_metric_type: "COSINE"
  
  # 稀疏向量配置
  sparse_field: "sparse_vector"
  sparse_metric_type: "IP"
  
  # 混合搜索配置
  hybrid_rrf_k: "60"
  
  # 嵌入模型配置
  use_fp16: "false"
  device: "cpu"

---
apiVersion: v1
kind: Secret
metadata:
  name: dify-external-kb-server-secret
type: Opaque
stringData:
  api_key: "t9k-12345"  # 生产环境应替换为强随机密钥
  milvus_token: ""
